name: Repository Dispatch
on: push
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: filiptronicek/filiptronicek
          event-type: blogpost
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'